"""Postgres-backed tools: full email content + semantic search.

These tools complement the Neo4j-backed catalog with access to the raw
email bodies and the per-email pgvector embeddings produced by Stage 1
(``orggraph.pipeline.email.embed``). Email nodes in Neo4j carry only
metadata (subject + date); the bodies and the 768-dim embeddings live
in the ``embeddings_email`` table in Postgres.

Factories take a ``pg_conn_factory`` callable that returns a context
manager yielding a registered psycopg connection. Tests inject a fake
connection; real callers use ``default_pg_conn_factory()`` from this
module, which opens connections from the ``PG_DSN`` env var with
pgvector type adapters registered.

Embeddings for the search tool are generated by ``embed_fn(text)``
which must use the SAME model that built the index (Ollama
``embeddinggemma``, 768-dim). ``default_embed_fn()`` reads
``EMBED_BASE_URL`` / ``EMBED_API_KEY`` / ``EMBED_MODEL`` from the
environment to match Stage 1.
"""

from __future__ import annotations

import os
from contextlib import contextmanager
from typing import Any, Callable

from orggraph.pipeline.agents.tools import KGTool, _safe


# Body length caps. The full-content tool returns up to ~4 KB so the model
# can read a real email; the search tool returns short excerpts so n=5
# results don't blow the context window.
BULK_BODY_TRUNC = 1200
BULK_SNIPPET_TRUNC = 320
EMAIL_BODY_FULL_TRUNC = 4000
ROLE_DESCRIPTION_TRUNC = 200
SEARCH_BODY_EXCERPT_TRUNC = 400
SPEECH_ACT_BODY_EXCERPT_TRUNC = 200
THREAD_BODY_EXCERPT_TRUNC = 300

# Speech-act vocabulary mirrors orggraph.pipeline.signals.extract.ALLOWED_SPEECH_ACTS;
# kept here as a tuple so the tool's args_schema can advertise the enum without
# importing the heavyweight signals package at registry-build time.
ALLOWED_SPEECH_ACTS = (
    "request", "commit", "deliver", "propose",
    "amend", "meeting", "refuse", "accept",
)


def make_get_email_content_tool(pg_conn_factory: Callable[[], Any]) -> KGTool:
    """Fetch full email content (subject + body + metadata) by email_id.

    Email IDs are stable identifiers returned by ``get_thread_history``
    and ``search_emails_semantic``. The model uses this when it needs
    the actual body content rather than just subject lines.
    """

    def _call(*, email_id: str) -> dict:
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(
                """
                SELECT email_id, subject, body_truncated, body_chars,
                       sender_resolved, recipients_resolved,
                       date::text, sentiment
                FROM embeddings_email
                WHERE email_id = %s
                """,
                (email_id,),
            )
            row = cur.fetchone()

        if row is None:
            return {"email_id": email_id, "found": False}

        eid, subject, body, body_chars, sender, recipients, date, sentiment = row
        body = (body or "").strip()
        truncated = False
        if len(body) > EMAIL_BODY_FULL_TRUNC:
            body = body[: EMAIL_BODY_FULL_TRUNC - 1].rstrip() + "…"
            truncated = True

        return {
            "email_id": eid,
            "found": True,
            "subject": _safe(subject),
            "body": body,
            "body_truncated": truncated,
            "body_chars": int(body_chars or 0),
            "date": date,
            "sender": _safe(sender),
            "recipients": list(recipients or []),
            "sentiment": float(sentiment) if sentiment is not None else None,
        }

    return KGTool(
        name="get_email_content",
        description=(
            "Fetch the full content of a single email by its email_id. Returns "
            "subject, body, date, sender, and recipients. Use after "
            "get_thread_history or search_emails_semantic to read the actual "
            "text of a specific email."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "email_id": {
                    "type": "string",
                    "description": "Stable email identifier from get_thread_history or search_emails_semantic.",
                },
            },
            "required": ["email_id"],
        },
        callable=_call,
    )


def make_search_emails_semantic_tool(
    pg_conn_factory: Callable[[], Any],
    embed_fn: Callable[[str], list[float]],
) -> KGTool:
    """Top-n emails most semantically similar to a natural-language query.

    Uses pgvector cosine similarity on the ``embedding`` column (768-d
    embeddinggemma vectors built by Stage 1). Returns body excerpts so
    the model can decide which IDs to pull in full via
    ``get_email_content``. Optional ``sender`` (canonical name) and
    ``before_date`` (ISO-8601) filters are applied before the cosine
    ranking.
    """

    def _call(
        *,
        query: str,
        n: int = 5,
        sender: str | None = None,
        before_date: str | None = None,
    ) -> list[dict]:
        vec = embed_fn(query)

        # Build the WHERE clause incrementally so optional filters stay
        # parametrised — never interpolate user-controlled values into
        # the SQL string.
        where_parts: list[str] = []
        filter_params: list[Any] = []
        if sender:
            where_parts.append("sender_resolved = %s")
            filter_params.append(sender)
        if before_date:
            where_parts.append("date < %s::timestamptz")
            filter_params.append(before_date)
        where_sql = ("WHERE " + " AND ".join(where_parts)) if where_parts else ""

        sql = f"""
            SELECT email_id, subject, body_truncated,
                   sender_resolved, date::text,
                   1 - (embedding <=> %s::vector) AS similarity
            FROM embeddings_email
            {where_sql}
            ORDER BY embedding <=> %s::vector
            LIMIT %s
        """
        # The vector parameter binds twice (SELECT expression + ORDER BY).
        params = [vec, *filter_params, vec, int(n)]

        out: list[dict] = []
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(sql, tuple(params))
            for row in cur.fetchall():
                eid, subject, body, snd, date, sim = row
                excerpt = (body or "").strip()
                if len(excerpt) > SEARCH_BODY_EXCERPT_TRUNC:
                    excerpt = excerpt[: SEARCH_BODY_EXCERPT_TRUNC - 1].rstrip() + "…"
                out.append({
                    "email_id": eid,
                    "subject": _safe(subject),
                    "sender": _safe(snd),
                    "date": date,
                    "body_excerpt": excerpt,
                    "similarity": float(sim) if sim is not None else None,
                })
        return out

    return KGTool(
        name="search_emails_semantic",
        description=(
            "Search the email corpus by semantic similarity to a natural-language "
            "query (pgvector cosine over 768-d embeddings). Returns top-n emails "
            "with subject + body excerpt + similarity score. Optional `sender` "
            "(canonical name) and `before_date` (ISO-8601 cutoff) filters. Use to "
            "find emails about a topic when you don't know the exact subject line."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Natural-language search query.",
                },
                "n": {"type": "integer", "minimum": 1, "default": 5},
                "sender": {
                    "type": ["string", "null"],
                    "description": "Optional: restrict to emails from this canonical sender name.",
                },
                "before_date": {
                    "type": ["string", "null"],
                    "description": "ISO-8601 cutoff. Only emails strictly before this are returned.",
                },
            },
            "required": ["query"],
        },
        callable=_call,
    )


def make_get_thread_tool(pg_conn_factory: Callable[[], Any]) -> KGTool:
    """Fetch every email in a thread, ordered by thread_position.

    A thread_id is shared across all emails in the same reply chain
    (set by Stage 1.5 metadata). This is how to read the full
    back-and-forth, not just one snapshot. Bodies are truncated to a
    short excerpt; the model can pull individual messages in full via
    ``get_email_content``.
    """

    def _call(*, thread_id: str, before_date: str | None = None) -> dict:
        params: list[Any] = [thread_id]
        date_filter = ""
        if before_date:
            date_filter = "AND date < %s::timestamptz"
            params.append(before_date)

        sql = f"""
            SELECT email_id, thread_position, subject, body_truncated,
                   sender_resolved, recipients_resolved, date::text
            FROM embeddings_email
            WHERE thread_id = %s
              {date_filter}
            ORDER BY thread_position ASC NULLS LAST, date ASC
        """
        emails: list[dict] = []
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(sql, tuple(params))
            for row in cur.fetchall():
                eid, pos, subject, body, sender, recipients, date = row
                excerpt = (body or "").strip()
                if len(excerpt) > THREAD_BODY_EXCERPT_TRUNC:
                    excerpt = excerpt[: THREAD_BODY_EXCERPT_TRUNC - 1].rstrip() + "…"
                emails.append({
                    "email_id": eid,
                    "thread_position": int(pos) if pos is not None else None,
                    "subject": _safe(subject),
                    "sender": _safe(sender),
                    "recipients": list(recipients or []),
                    "date": date,
                    "body_excerpt": excerpt,
                })

        return {
            "thread_id": thread_id,
            "n_emails": len(emails),
            "emails": emails,
        }

    return KGTool(
        name="get_thread",
        description=(
            "Fetch every email in a thread (shared thread_id), ordered. Use "
            "after get_thread_history when you have one email_id and want the "
            "full back-and-forth context. Returns short body excerpts; pull "
            "individual emails in full via get_email_content."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "thread_id": {
                    "type": "string",
                    "description": "Thread identifier shared by all emails in the chain.",
                },
                "before_date": {
                    "type": ["string", "null"],
                    "description": "ISO-8601 cutoff. Only thread emails strictly before this are returned.",
                },
            },
            "required": ["thread_id"],
        },
        callable=_call,
    )


def make_get_pair_signals_tool(pg_conn_factory: Callable[[], Any]) -> KGTool:
    """Dyadic communication signals between two people.

    Returns the row from ``pair_signals`` aggregated by Stage 3:
    n_emails, request/commit balance, mean sentiment, mean reply
    latency, length asymmetry, etc. The model uses this to reason
    quantitatively about a relationship instead of inferring tone
    from a few subject lines.
    """

    def _call(**kwargs) -> dict:
        # Canonical signature is (sender, recipient). Some models hallucinate
        # generic graph-DB parameter names like (name1, name2) or
        # (person_a, person_b); we accept those as aliases rather than fail
        # validation on every retry.
        sender = (kwargs.get("sender") or kwargs.get("name1")
                  or kwargs.get("person_a"))
        recipient = (kwargs.get("recipient") or kwargs.get("name2")
                     or kwargs.get("person_b"))
        if not sender or not recipient:
            return {"error": "MissingArgs",
                    "tool": "get_pair_signals",
                    "details": "Required: sender + recipient (also accepts "
                               "name1+name2 or person_a+person_b)."}
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(
                """
                SELECT n_emails, n_to, n_cc,
                       n_request_sent, n_commit_sent, n_deliver_sent, n_propose_sent,
                       n_decision, n_action_required,
                       request_commit_ratio, mean_reply_latency_h,
                       mean_sentiment, mean_body_words, length_asymmetry,
                       first_email_date::text, last_email_date::text
                FROM pair_signals
                WHERE sender_id = %s AND recipient_id = %s
                """,
                (sender, recipient),
            )
            row = cur.fetchone()

        if row is None:
            return {
                "sender": sender,
                "recipient": recipient,
                "found": False,
            }

        (n_emails, n_to, n_cc, n_req, n_com, n_del, n_pro, n_dec, n_act,
         rc_ratio, mean_lat, mean_sent, mean_words, len_asym,
         first_date, last_date) = row

        def _f(v):
            return float(v) if v is not None else None

        return {
            "sender": sender,
            "recipient": recipient,
            "found": True,
            "n_emails": int(n_emails or 0),
            "n_to": int(n_to or 0),
            "n_cc": int(n_cc or 0),
            "speech_acts": {
                "n_request_sent": int(n_req or 0),
                "n_commit_sent": int(n_com or 0),
                "n_deliver_sent": int(n_del or 0),
                "n_propose_sent": int(n_pro or 0),
            },
            "n_decision": int(n_dec or 0),
            "n_action_required": int(n_act or 0),
            "request_commit_ratio": _f(rc_ratio),
            "mean_reply_latency_hours": _f(mean_lat),
            "mean_sentiment": _f(mean_sent),
            "mean_body_words": _f(mean_words),
            "length_asymmetry": _f(len_asym),
            "first_email_date": first_date,
            "last_email_date": last_date,
        }

    return KGTool(
        name="get_pair_signals",
        description=(
            "Quantitative signals for one DIRECTED email pair. "
            "REQUIRED args: `sender` (canonical name of who sends), "
            "`recipient` (canonical name of who receives). "
            "Returns email volume, speech-act counts (requests / commits / "
            "deliveries / proposes), mean sentiment, mean reply latency, "
            "length asymmetry, decision and action-required counts. Use to "
            "reason quantitatively about a relationship's tone and dynamics "
            "instead of guessing from subject lines. "
            "Example: get_pair_signals(sender='David Delainey', "
            "recipient='John Lavorato')."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "sender": {
                    "type": "string",
                    "description": "Canonical name of the sender.",
                },
                "recipient": {
                    "type": "string",
                    "description": "Canonical name of the recipient.",
                },
                # Aliases — accepted but undocumented. Some models hallucinate
                # generic graph-DB names; rather than fail validation we
                # accept them and remap inside _call.
                "name1": {"type": "string"},
                "name2": {"type": "string"},
                "person_a": {"type": "string"},
                "person_b": {"type": "string"},
            },
            "anyOf": [
                {"required": ["sender", "recipient"]},
                {"required": ["name1", "name2"]},
                {"required": ["person_a", "person_b"]},
            ],
        },
        callable=_call,
    )


def make_find_person_tool(
    pg_conn_factory: Callable[[], Any],
    embed_fn: Callable[[str], list[float]],
) -> KGTool:
    """Semantic person lookup via cosine similarity over
    ``embeddings_person`` (768-d Stage 7 embeddings).

    Handles both plain name lookups and natural-language role
    descriptions. The embedding text bundles title, role summary,
    function, persona, top topics, and frequent contacts.
    """

    def _call(*, query: str, k: int = 5) -> list[dict]:
        vec = embed_fn(query)
        sql = """
            SELECT person_id, name, role, department,
                   1 - (embedding <=> %s::vector) AS similarity
            FROM embeddings_person
            ORDER BY embedding <=> %s::vector
            LIMIT %s
        """
        out: list[dict] = []
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(sql, (vec, vec, int(k)))
            for row in cur.fetchall():
                pid, name, role, dept, sim = row
                role_short = _safe(role)
                if len(role_short) > ROLE_DESCRIPTION_TRUNC:
                    role_short = role_short[: ROLE_DESCRIPTION_TRUNC - 1].rstrip() + "…"
                out.append({
                    "name": _safe(name),
                    "person_id": _safe(pid),
                    "role": role_short,
                    "department": _safe(dept),
                    "similarity": float(sim) if sim is not None else None,
                })
        return out

    return KGTool(
        name="find_person",
        description=(
            "Find people by name, partial name, role, or natural-language "
            "description. Returns top-k canonical persons by cosine similarity "
            "over per-person embeddings (title + role summary + function + top "
            "topics + frequent contacts). Use whenever you need a canonical "
            "person name or you do not know who handles a topic."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Person name, partial name, role, or natural-language description.",
                },
                "k": {"type": "integer", "minimum": 1, "default": 5},
            },
            "required": ["query"],
        },
        callable=_call,
    )


def make_find_emails_tool(pg_conn_factory: Callable[[], Any]) -> KGTool:
    """Find emails matching any combination of structured filters."""

    def _call(
        *,
        sender: str | None = None,
        recipient: str | None = None,
        before_date: str | None = None,
        after_date: str | None = None,
        speech_act: str | None = None,
        topic: str | None = None,
        subject_contains: str | None = None,
        body_contains: str | None = None,
        decision_carrying: bool | None = None,
        action_required: bool | None = None,
        sentiment_min: float | None = None,
        sentiment_max: float | None = None,
        n: int = 10,
    ) -> list[dict] | dict:
        # require at least ONE filter — otherwise full-table scan
        active = any(v is not None for v in (
            sender, recipient, before_date, after_date, speech_act, topic,
            subject_contains, body_contains, decision_carrying, action_required,
            sentiment_min, sentiment_max,
        ))
        if not active:
            return {"error": "InvalidArgs", "details": "find_emails requires at least one filter"}

        # validate speech_act against ALLOWED_SPEECH_ACTS if provided
        if speech_act and speech_act not in ALLOWED_SPEECH_ACTS:
            return {"error": f"Unknown speech_act {speech_act!r}; allowed: {list(ALLOWED_SPEECH_ACTS)}"}

        params: list[Any] = []
        clauses: list[str] = []
        if sender:
            clauses.append("sender_resolved = %s")
            params.append(sender)
        if recipient:
            clauses.append("recipients_resolved ? %s")
            params.append(recipient)
        if before_date:
            clauses.append("date < %s::timestamptz")
            params.append(before_date)
        if after_date:
            clauses.append("date >= %s::timestamptz")
            params.append(after_date)
        if speech_act:
            clauses.append("speech_acts ? %s")
            params.append(speech_act)
        if topic:
            clauses.append("topics ? %s")
            params.append(topic)
        if subject_contains:
            clauses.append("subject ILIKE %s")
            params.append(f"%{subject_contains}%")
        if body_contains:
            clauses.append("body_truncated ILIKE %s")
            params.append(f"%{body_contains}%")
        if decision_carrying is not None:
            clauses.append("decision_carrying = %s")
            params.append(bool(decision_carrying))
        if action_required is not None:
            clauses.append("action_required = %s")
            params.append(bool(action_required))
        if sentiment_min is not None:
            clauses.append("sentiment >= %s")
            params.append(float(sentiment_min))
        if sentiment_max is not None:
            clauses.append("sentiment <= %s")
            params.append(float(sentiment_max))

        where_sql = " AND ".join(clauses)
        params.append(int(n))

        sql = f"""
            SELECT email_id, subject, body_truncated,
                   sender_resolved, recipients_resolved,
                   date::text, speech_acts, topics, sentiment,
                   decision_carrying, action_required
            FROM embeddings_email
            WHERE {where_sql}
            ORDER BY date DESC
            LIMIT %s
        """
        out: list[dict] = []
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(sql, tuple(params))
            for row in cur.fetchall():
                eid, subject, body, snd, recipients, date, acts, topics, sentiment, dc, ar = row
                excerpt = (body or "").strip()
                if len(excerpt) > SPEECH_ACT_BODY_EXCERPT_TRUNC:
                    excerpt = excerpt[: SPEECH_ACT_BODY_EXCERPT_TRUNC - 1].rstrip() + "…"
                out.append({
                    "email_id": eid,
                    "subject": _safe(subject),
                    "sender": _safe(snd),
                    "recipients": list(recipients or []),
                    "date": date,
                    "speech_acts": list(acts or []),
                    "topics": list(topics or []),
                    "sentiment": float(sentiment) if sentiment is not None else None,
                    "decision_carrying": bool(dc) if dc is not None else None,
                    "action_required": bool(ar) if ar is not None else None,
                    "body_excerpt": excerpt,
                })
        return out

    return KGTool(
        name="find_emails",
        description=(
            "Find emails matching any combination of structured filters. "
            "At least one filter must be provided. All filters compose with AND. "
            "Filters: sender (canonical name, exact), recipient (canonical name, "
            "matches recipients_resolved jsonb), before_date / after_date "
            "(ISO-8601), speech_act (one of: request, commit, deliver, propose, "
            "amend, meeting, refuse, accept), topic (matches topics jsonb), "
            "subject_contains / body_contains (case-insensitive substring), "
            "decision_carrying / action_required (boolean), "
            "sentiment_min / sentiment_max (numeric range). Results ordered by "
            "date DESC."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "sender":             {"type": ["string", "null"]},
                "recipient":          {"type": ["string", "null"]},
                "before_date":        {"type": ["string", "null"], "description": "ISO-8601 timestamp; emails strictly before this."},
                "after_date":         {"type": ["string", "null"], "description": "ISO-8601 timestamp; emails on/after this."},
                "speech_act":         {"type": ["string", "null"], "enum": [None] + list(ALLOWED_SPEECH_ACTS)},
                "topic":              {"type": ["string", "null"], "description": "Topic name in topics jsonb (exact match)."},
                "subject_contains":   {"type": ["string", "null"]},
                "body_contains":      {"type": ["string", "null"]},
                "decision_carrying":  {"type": ["boolean", "null"]},
                "action_required":    {"type": ["boolean", "null"]},
                "sentiment_min":      {"type": ["number", "null"]},
                "sentiment_max":      {"type": ["number", "null"]},
                "n":                  {"type": "integer", "minimum": 1, "default": 10},
            },
            "required": [],
        },
        callable=_call,
    )


def _extract_snippet(body: str, focus: str, max_chars: int) -> str:
    """Return up to ``max_chars`` characters of ``body`` centred on the first
    case-insensitive match of ``focus``. Falls back to the leading slice."""
    if not body or not focus:
        return body[:max_chars]
    idx = body.lower().find(focus.lower())
    if idx < 0:
        return body[:max_chars]
    half = max_chars // 2
    start = max(0, idx - half)
    end = min(len(body), start + max_chars)
    start = max(0, end - max_chars)  # recover left slack if end was clamped
    return body[start:end]


def make_get_emails_bulk_tool(pg_conn_factory: Callable[[], Any]) -> KGTool:
    """Fetch N emails in one round-trip, optionally with focus-keyed snippets."""

    def _call(*, ids: list[str], focus: str | None = None) -> list[dict]:
        ids = [str(x) for x in (ids or []) if x]
        if not ids:
            return []
        sql = (
            "SELECT email_id, date::text, sender_resolved, subject, body_truncated "
            "FROM embeddings_email "
            "WHERE email_id = ANY(%s) "
            "ORDER BY array_position(%s::text[], email_id)"
        )
        out: list[dict] = []
        with pg_conn_factory() as conn, conn.cursor() as cur:
            cur.execute(sql, (ids, ids))
            for email_id, date, sender, subject, body in cur.fetchall():
                body = body or ""
                row = {
                    "email_id": email_id,
                    "date": _safe(date),
                    "sender": _safe(sender),
                    "subject": _safe(subject),
                    "body": body[:BULK_BODY_TRUNC],
                }
                if focus:
                    row["snippet"] = _extract_snippet(body, focus, BULK_SNIPPET_TRUNC)
                out.append(row)
        return out

    return KGTool(
        name="get_emails_bulk",
        description=(
            "Fetch the bodies of N emails in one call. Use after "
            "search_emails_semantic to read the candidate emails together. "
            "Optional `focus` keyword returns a short snippet from each body "
            "centred on the closest match to the focus string."
        ),
        args_schema={
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {"type": "string"},
                    "minItems": 1,
                    "maxItems": 20,
                    "description": "List of string email_id values from search_emails_semantic or get_thread results. At most 20.",
                },
                "focus": {
                    "type": ["string", "null"],
                    "description": "Optional keyword; if set, each row carries a snippet.",
                },
            },
            "required": ["ids"],
        },
        callable=_call,
    )


# --- default factories (env-derived) ----------------------------------------


def _build_pg_dsn() -> str:
    """Construct the default PG_DSN from POSTGRES_* env vars (mirrors the
    pattern used throughout ``orggraph.pipeline``)."""
    return os.environ.get(
        "PG_DSN",
        f"postgresql://{os.environ.get('POSTGRES_USER','orggraph')}:"
        f"{os.environ.get('POSTGRES_PASSWORD','orggraph2026')}@localhost:"
        f"{os.environ.get('POSTGRES_PORT','5432')}/"
        f"{os.environ.get('POSTGRES_DB','orggraph')}",
    )


def default_pg_conn_factory() -> Callable[[], Any]:
    """Returns a callable that yields a fresh psycopg connection with
    pgvector type adapters registered. Imported lazily so non-Postgres
    test paths don't pull in psycopg / pgvector.
    """
    import psycopg
    from pgvector.psycopg import register_vector

    dsn = _build_pg_dsn()

    @contextmanager
    def _open():
        with psycopg.connect(dsn) as conn:
            register_vector(conn)
            yield conn

    return _open


def default_embed_fn() -> Callable[[str], list[float]]:
    """Returns a callable that embeds a single text via the env-configured
    Ollama endpoint (same model as Stage 1, so query vectors live in the
    same space as the indexed corpus)."""
    from openai import OpenAI

    base_url = os.environ.get("EMBED_BASE_URL", "http://localhost:11434/v1")
    api_key = os.environ.get("EMBED_API_KEY", "ollama")
    model = os.environ.get("EMBED_MODEL", "embeddinggemma")
    client = OpenAI(base_url=base_url, api_key=api_key)

    def _embed(text: str) -> list[float]:
        resp = client.embeddings.create(model=model, input=[text])
        return resp.data[0].embedding

    return _embed
